# Generated by Django 5.2.8 on 2025-12-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='company',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='student',
        ),
        migrations.DeleteModel(
            name='PlacementStatistic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Placement',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
